# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maarten Scholz
email: maarten.scholz@gmail.com
description: "Software enigeer for <a href='https://madewithlove.be' target='_blank'>madewithlove</a>. Easliy confused."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maartenscholz.github.io" # the base hostname & protocol for your site
twitter_username: maartenscholz
github_username:  maartenscholz
permalink: "/posts/:title/"

# Build settings
markdown: kramdown
